version: '3'
services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PORT=3306
      - API_PORT=4000
      - API_SECRET=09f26e402586e2faa8da4c98a35f1b20d6b033c60
    depends_on:
      - mysql
    command: sh -c 'sleep 10; npm start'
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# -----------------------
#  Optionnel : Serveur phpmyadmin
# -----------------------
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=mysql
#    ports:
#      - "8080:80"
#    depends_on:
#      - mysql